name: Build and publish docker image
on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget -O run https://raw.githubusercontent.com/minidocks/images/master/run
      - run: sh ./run github:build
      - env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: sh ./run github:push
